#!/usr/bin/env bash
# ----------------------------------------------------------------------------
DAILY_CALS_DEFAULT=1850
SUNDAY_CALS_DEFAULT=$DAILY_CALS_DEFAULT

function usage
{
    cat <<EOF >&2
$(basename $0) [-d <daily-cals=$DAILY_CALS_DEFAULT>] [-s <sunday-cals=$SUNDAY_CALS_DEFAULT>]
$(basename $0) {-h | --help}

    -d specifies the average daily intake, default=$DAILY_CALS_DEFAULT
    -h print this help/usage information
    -s specifies calories for Sunday, default=$SUNDAY_CALS_DEFAULT
EOF
}

case $1 in -h|--help)
    usage
    exit 0
    ;;
esac

# ----------------------------------------------------------------------------
declare -A day_calories

# establish defaults
day_calories["sunday"]=$SUNDAY_CALS_DEFAULT
daily_cals=$DAILY_CALS_DEFAULT

# parse command-line options, which override defaults
while getopts "d:s:" option; do
    case $option in
        d)
            daily_cals=$OPTARG
            ;;
        s)
            day_calories["sunday"]=$OPTARG
            ;;
    esac
done

# shift non-option arguments to begin at $1
shift $(( OPTIND - 1 ))

weekly_cals=$((daily_cals * 7))
weekday_cals=$(dc -e "0k $weekly_cals 2/ p")
weekend_cals=$weekday_cals

# ----------------------------------------------------------------------------
# calculation
# ----------------------------------------------------------------------------

if (( ${day_calories["sunday"]} > $daily_cals )); then
    echo daily calories \($daily_cals\) must be at least sunday\'s \(${day_calories["sunday"]}\)
    exit 1
fi

for d in monday tuesday wednesday thursday; do
    day_calories["$d"]=$(dc -e "0k $weekday_cals 4/ p")
done

fri_sat_cals=$(dc -e "0k $weekend_cals ${day_calories["sunday"]}- p")

day_calories["friday"]=$(dc -e "0k $fri_sat_cals 2/ p")
day_calories["saturday"]=${day_calories["friday"]}

# ----------------------------------------------------------------------------
# output
# ----------------------------------------------------------------------------
echo daily calories: $daily_cals
echo weekly calories: $weekly_cals
echo weekdays calories: $weekday_cals
echo weekend calories: $weekend_cals

sum=0
for d in sunday monday tuesday wednesday thursday friday saturday; do
    echo $d ${day_calories["$d"]}
    sum=$((sum + ${day_calories["$d"]}))
done

echo missing calories: $(( weekly_cals - sum ))
